env:
  global:
  - GCP_PROJECT_ID=devops05-290206
  - tf_version=0.13.3
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: J6OlmLv1PRzuSPWbfrtc/KsFuetfO0sR1XykfdlBKQ/SDYX+kq2xeTFrxYo/mYM6Wb3HFB3zQfdwjMXMoSEnsbDYNlODEiGTKdVhE/ODUtrnE//n4u2b60hGZrtW4/mmKHOgX+4sZpA/1YIMc9cmRZ3wkmGXQ6RCXACMt4AP6VEh9Zrk5uS0giJ11EZSZ08HUHWQo39tlIDjEeqFkvRRp0vvtf/hBNvw2elG79y3x0Cfju9O0WDoc94sqz71+/QvjBNxGrWsNL0bz6INyUfzsaOD9yCGtwCuSAfZtwFncL2aOFg9wyvI1P+mMnnwPzcNvnyZy4R4knASnV57hQjBzghIesnWYdTyieDC3/5AA73m027dAnzKgwfTZ2vyPq0QSYbBjy+q0KV1n9a19TXPxWgR2OYllvw0vRO4ln72KpX6pH37lK6fGqy/FaYSJmyva3F+uCyNyxq4kUATE5Y3bXj2vNePlw6vSaoAqeR2H7LM8Xj0vBnXHoJv+Rjkkp2+SXEfvcjd0AjApDVXVCfqHNQzgmD6G0JVwAS5zbfiq0vDL9tdg4g9QuP3Dtd43hQRjg7VPo7XxP1fl4VuagIY26LQ0tHJ7lznhHNHsajs+NPOFI2003yla6iB6GsmAPd6AqZtdBSZOhBLIb5CBVojmacSbE7JJgm3AD0RB9vv/M4=
  - secure: OUgFZaPF/8D2c0R41SbpRH1FYHBgpWgm4udpJSwVDpkvHQht9fVUJeY4hEjW1fbs5SbBpCPzy9IcJtasC65m52Rai1jquhxnONhas+2M6R+AlRxscRW5fW5iDhfHilvHAR3A4OjNJawSNsuT3nyklaggMIcqa8qw/njGRVOSvIbZoP6TPIRbTsAHgdbg0GUKX7746hQufeP6sopFC83b4bh6dNvmBxmJqxY4eN5cLkdMpz7mAHeorf3qp8j8xKQy7Olcnh/RAT7gMKwHDfJgpp8iv/CzcOumPuu6gZpqDvf8vTs9eb6yQ/CwFjt7oT6ctoKg4/5gTLPas/3TC02SClZkVfMUZeeq9eOhBGsrwS/XW5ktj6xpJVMKYlDEsqoVBo5hVNIP8dBlRFf+ifWDGV7BnSjUTSEMHty7/Iq+3ELkDcnIPBNxLzbOu3BI42ImjTGObbu37QR+kxPi/T9E4ZIC8rNb7ONimh0uwMcARajfyeJoV8DGi4tizTwl3y6L0vzIGsehJKxEl9ZNdQk4c4Q5aFNatoDWxTgNNQTRsejgST31ih7yZRfECOCc9sHD6gZogCGv+NpqPTcsD5DdNkVMil6NlDnZCuWX1AV5uxrcKFq44mrIQ8DYPVGd/8zh1qW7OrY/O0lT6fCM1Ma95JnnyW8opeVP54ki6aqzf+Q=
  - secure: gku/xmIxg5mhzCI+cVQHS+7Hk66F4oQsEORnVjbkBd/v79SJYAvQSGyf05eIZR0MCDGVlid+rnJ4zUkznX9Y7TwgJgg9yRhscapoJccSvL3hswOhW7MRC/zFl5D6u4Z0CPbgmFDl80FtwSGxF/rGiYuRMEC9XQpfHyxGoow4qgwaiXtsUe5ORkMalM4a8KgVj1umjjO7LbrM4BUa8TO/PYQAnuW/iMetZwDrkh+VHAIQZjVa7dPELaZrxW56yNyEr8Gj3OWSIsD2BjXQNcu+viyeMj6qdpYzS93ozRftIgNJq6tM4EOJEXdYZwkNjMw5fVDyNgsG8Ag3cyGOGrDBBWQ0Ph5uhTsMERzGDlssQ2ypTadwBwkBn86xIwOajy8j6toSoOiVReszTfCpJrdOOq8GX39L3YCQdfMOYcL/ERmNsMaNJ7et70icKxGhw8m+c4yEpuvZhCOCPx2pAv/yOoqTkqra29kh1vl0bOcd0GBCo2gNog/qYFvQX6yzDGzRILZfJHl3BFxtXW9wQvx5fb+ZJXgG9+pJGgtQoCmTlA1Vqn7o+NN56SPg4wZAofN4VyCm77d2t9OE9yD8ynC//X/05y6oiJ36VFGE/mtpxOWuB1kZDCa5ElAaFov5mhSDq91d/m/2a3Zo2EUG4Ry2qk+7E7XZ1k0MsHIAnMrM8ZY=
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_98d237b7dbf4_key -iv $encrypted_98d237b7dbf4_iv
  -in google-key.json.enc -out google-key.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=google-key.json
- gcloud config set project "${GCP_PROJECT_ID}"
- export GOOGLE_APPLICATION_CREDENTIALS=./google-key.json
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
- |-
  set -ex;
  export TF_VAR_logz_token=$LOGZ_TOKEN
  terraform init
  terraform plan
  terraform apply --auto-approve
  terraform output
